# ==========================================
# Configurazione Applicativa - The Knife (Client)
# ==========================================

app.name=TheKnife-Client
app.versione=1.0.0

# ==========================================
# Configurazione Connessione al Server RMI
# ==========================================
# L'indirizzo IP o il dominio dove risiede il serverTK
server.host=127.0.0.1

# La porta del LocateRegistry (deve coincidere con rmi.port del server)
server.rmi.port=1099

# Il nome del servizio da cercare (deve coincidere con rmi.service.name del server)
server.rmi.service.name=TheKnifeService