# ==========================================
# Configurazione Applicativa - The Knife (Server)
# ==========================================

# Identificativo dell'applicazione
app.name=TheKnife-Server
app.versione=1.0.0

# ==========================================
# Configurazione RMI (Remote Method Invocation)
# ==========================================
# La porta su cui il LocateRegistry rimarrà in ascolto
rmi.port=1099

# Il nome univoco con cui il servizio verrà registrato (Binding Name)
rmi.service.name=TheKnifeService

# (Opzionale) Forza l'hostname per evitare problemi di binding su reti multi-interfaccia
java.rmi.server.hostname=127.0.0.1